#!/bin/bash

################################################################################
#
# Generate Amazon Linux based Dockerfile for deployment on ECR.
#
################################################################################

EPEL_RPM=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

cat Dockerfile \
  | sed -e 's!^FROM .*$!FROM amazonlinux!g' \
        -e 's!apt-get update!yum update -y \&\& yum install -y '"$EPEL_RPM"'!g' \
        -e 's!apt-get!yum!g' \
        -e 's!p7zip-full!p7zip p7zip-plugins!g' \
        -e 's!qemu-kvm!!g' \
        -e 's!rm -rf /var/lib/apt/lists/\*!true!g' \
        -e '/# BUILD:QEMU/ a\
        ADD support/install-qemu.sh .' \
        -e '/# BUILD:QEMU/ a\
        RUN chmod +x ./install-qemu.sh && ./install-qemu.sh && rm ./install-qemu.sh' \
  > Dockerfile.amazonlinux
